// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: follow_feeds.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFollowFeed = `-- name: CreateFollowFeed :one
WITH inserted_follow_feed AS(
INSERT INTO follow_feeds(id,user_id,feed_id,created_at,updated_at)
VALUES($1,$2,$3,$4,$5) RETURNING id, user_id, feed_id, created_at, updated_at
)SELECT inserted_follow_feed.id, inserted_follow_feed.user_id, inserted_follow_feed.feed_id, inserted_follow_feed.created_at, inserted_follow_feed.updated_at,
feeds.name AS feed_name,
users.name AS user_name
from inserted_follow_feed INNER JOIN feeds ON inserted_follow_feed.feed_id = feeds.id
INNER JOIN users ON inserted_follow_feed.user_id = users.id
`

type CreateFollowFeedParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	FeedID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type CreateFollowFeedRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	FeedID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	FeedName  string
	UserName  string
}

func (q *Queries) CreateFollowFeed(ctx context.Context, arg CreateFollowFeedParams) (CreateFollowFeedRow, error) {
	row := q.db.QueryRowContext(ctx, createFollowFeed,
		arg.ID,
		arg.UserID,
		arg.FeedID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CreateFollowFeedRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FeedID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FeedName,
		&i.UserName,
	)
	return i, err
}

const getFollowFeedsForUser = `-- name: GetFollowFeedsForUser :many
SELECT follow_feeds.id, follow_feeds.user_id, follow_feeds.feed_id, follow_feeds.created_at, follow_feeds.updated_at,feeds.name AS feed_name FROM follow_feeds 
INNER JOIN feeds ON follow_feeds.feed_id = feeds.id WHERE follow_feeds.user_id = $1
`

type GetFollowFeedsForUserRow struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	FeedID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	FeedName  string
}

func (q *Queries) GetFollowFeedsForUser(ctx context.Context, userID uuid.UUID) ([]GetFollowFeedsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getFollowFeedsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFollowFeedsForUserRow
	for rows.Next() {
		var i GetFollowFeedsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FeedID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FeedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unfollowFeed = `-- name: UnfollowFeed :exec
DELETE from follow_feeds WHERE user_id =$1 and feed_id=$2
`

type UnfollowFeedParams struct {
	UserID uuid.UUID
	FeedID uuid.UUID
}

func (q *Queries) UnfollowFeed(ctx context.Context, arg UnfollowFeedParams) error {
	_, err := q.db.ExecContext(ctx, unfollowFeed, arg.UserID, arg.FeedID)
	return err
}
